export const banks = [
    {
        name: 'Bancolombia',
        credit: {
            type: ['Hipotecario'],
            percentage_vis: '80',
            percentage_novis: '70',
            type_of_fee: ['Pesos'],
            time_limit_min: 5,
            time_limit_max: 20,
            min_age: 23,
            max_age: 72,
        },
        interest_rate: {
            year: 0.1515,
            month: 0.0118,
        },
        migratory_state: {
            state: 'Definido',
            validity: 3,
        },
        incomes: 3480000,
        score: 600,
        economic_activity: ['Empleado', 'Pensionado', 'Independiente'],
        contract: ['Indefinido'],
        current_job: 12,
        ceased_period: 1.16,
        countries: [
            'España',
            'Belgica',
            'Paises Bajos',
            'Suiza',
            'Italia',
            'Francia',
            'Alemania',
            'Escocia',
            'Gales',
            'Inglaterra',
            'Irlanda del Norte',
            'Estados Unidos',
            'Canadá',
            'Puerto Rico',
            'Chile',
            'Panamá',
            'Salvador',
            'México',
            'Costa Rica',
            'Perú',
            'Emiratos Árabes',
        ],
        foreign_vinculation: {
            relationships: ['Padres', 'Hijos', 'Conyugue'],
            incomes: 0,
        },
    },

    {
        name: 'Davivienda',

        credit: {
            type: ['Hipotecario', 'Leasing habitacional'],
            percentage_vis: '80',
            percentage_novis: '70',
            type_of_fee: ['Pesos', 'UVR'],
            time_limit_min: 5,
            time_limit_max: 20,
            time_limit_max_uvr: 30,
            min_age: 18,
            max_age: 70,
        },
        interest_rate: {
            year: 0.1817,
            month: 0.014,
        },
        migratory_state: {
            state: 'Definido',
            validity: 3,
        },
        incomes: 1160000,
        score: 600,
        economic_activity: ['Empleado', 'Pensionado', 'Independiente'],
        current_job: 12,
        ceased_period: 3,
        countries: [
            'España',
            'Francia',
            'Inglaterra',
            'Suiza',
            'Alemania',
            'Bélgica',
            'Holanda',
            'Chile',
            'Canadá',
            'Estados Unidos',
            'México',
            'Costa Rica',
            'Australia',
        ],
        foreign_vinculation: {
            relationships: ['Padres', 'Hijos', 'Conyugue'],
            incomes: 1000000,
        },
    },

    {
        name: 'Banco Unión',
        credit: {
            type: ['Hipotecario', 'Libre inversión'],
            percentage_vis: '80',
            percentage_novis: '70',
            percentage_vis_libre: '50',
            type_of_fee: ['Pesos'],
            time_limit_min: 5,
            time_limit_max: 15,
            time_limit_max_uvr: 7,
            min_age: 18,
            max_age: 64,
        },
        interest_rate: {
            year: 0.165,
            month: 0.0128,
        },
        migratory_state: {
            state: 'Definido',
            validity: 0,
        },
        incomes: 1160000,
        score: 600,
        economic_activity: ['Empleado', 'Pensionado', 'Independiente'],
        current_job: 12,
        ceased_period: 3,
        countries: ['Venezuela', 'Rusia', 'Irán', 'Irak', 'Turquía', 'Cuba'],
        foreign_vinculation: {
            relationships: ['Padres', 'Hijos', 'Conyugue'],
            incomes: 0,
        },
    },
]
