const { DataTypes } = require('sequelize')
const db = require('../database/db')

const Client = db.define('clients', {
    name: { type: DataTypes.STRING, allowNull: false },
    last_name: { type: DataTypes.STRING, allowNull: false },
    email: { type: DataTypes.STRING, allowNull: false },
    phone: { type: DataTypes.STRING, allowNull: false },
    identification: { type: DataTypes.STRING, allowNull: false },
    number_identification: { type: DataTypes.STRING, allowNull: false },
    expedition_date: { type: DataTypes.DATE },
    birth_date: { type: DataTypes.DATE },
    country_residence: { type: DataTypes.STRING, allowNull: false },
    country: { type: DataTypes.STRING, allowNull: false },
    identification_migration: { type: DataTypes.STRING, allowNull: false },
    number_migration: { type: DataTypes.STRING, allowNull: false },
    expiration_day: { type: DataTypes.DATE },
    migratory_state: { type: DataTypes.STRING, allowNull: false },
    civil_status: { type: DataTypes.STRING, allowNull: false },
    level_study: { type: DataTypes.STRING, allowNull: false },
    state_residence: { type: DataTypes.STRING, allowNull: false },
    housing_type: { type: DataTypes.STRING, allowNull: false },
    canal: { type: DataTypes.STRING },
    economic_activity: { type: DataTypes.STRING, allowNull: false },
    type_contract: { type: DataTypes.STRING, allowNull: false },
    current_job: { type: DataTypes.DATE },
    previous_job: { type: DataTypes.DATE },
    retirement_job: { type: DataTypes.DATE },
    currency: { type: DataTypes.STRING, allowNull: false },
    monthly_income: { type: DataTypes.STRING, allowNull: false },
    others_income: { type: DataTypes.STRING, allowNull: false },
    foreign_income: { type: DataTypes.STRING, allowNull: false },
    total_income: { type: DataTypes.STRING },
    account_holder: { type: DataTypes.STRING, allowNull: false},
    rental_expense: { type: DataTypes.STRING },
    draft_expense: { type: DataTypes.STRING },
    family_cost: { type: DataTypes.STRING },
    sustaining_expense: { type: DataTypes.STRING },
    mortgage_credit: { type: DataTypes.STRING },
    credit_card: { type: DataTypes.STRING },
    fee_credits: { type: DataTypes.STRING },
    mortgage_credits: { type: DataTypes.STRING },
    total_expense: { type: DataTypes.STRING },
    number_tdc: { type: DataTypes.STRING },
    total_quota: { type: DataTypes.STRING },
    income_tax: { type: DataTypes.BOOLEAN },
    property_value: { type: DataTypes.STRING },
    property_state: { type: DataTypes.STRING, allowNull: false },
    modality: { type: DataTypes.STRING },
    type_credit: { type: DataTypes.STRING, allowNull: false },
    credit_value: { type: DataTypes.STRING, allowNull: false },
    type_fee: { type: DataTypes.STRING, allowNull: false },
    deadline: { type: DataTypes.STRING, allowNull: false },
    related_person: { type: DataTypes.BOOLEAN },
    coowner1: { type: DataTypes.STRING, allowNull: true},
    coowner2: { type: DataTypes.STRING, allowNull: true},
    coowner3: { type: DataTypes.STRING, allowNull: true},
    headline_income: { type: DataTypes.BOOLEAN, allowNull: true },
    certified_income: { type: DataTypes.STRING, allowNull: false },
    relationship_holder: { type: DataTypes.STRING, allowNull: true },
    nationality_holder: { type: DataTypes.STRING, allowNull: true },
    country_holder: { type: DataTypes.STRING, allowNull: true },
    foreign_affiliation: { type: DataTypes.BOOLEAN },
    relationship_foreigner: { type: DataTypes.STRING, allowNull: true },
    income_holder: { type: DataTypes.BOOLEAN, allowNull: true },
    certified_income_holder: { type: DataTypes.STRING, allowNull: true },
    data_authorization: { type: DataTypes.BOOLEAN, allowNull: false },
    risks_authorization: { type: DataTypes.BOOLEAN, allowNull: false },
    conditions_authorization: { type: DataTypes.BOOLEAN, allowNull: false },
    pre_approved: { type: DataTypes.DOUBLE, allowNull: true },
    monthly_fee: { type: DataTypes.DOUBLE, allowNull: true },
    trm: { type: DataTypes.DOUBLE, allowNull: true },
})
module.exports = Client